### ISSUE TITLE
It's not working properly.

### ISSUE THREAD

**Issue by rubyon** [marcdubois71450/tesla-carplay#1]
I followed as much as possible.

-----
root@carplay:/home/pi/tesla-carplay# node index.js
spawning carplay {
  dpi: 15,
  nightMode: 0,
  hand: 0,
  boxName: 'nodePlay',
  width: 848,
  height: 717,
  fps: 30
}
directory found
device connected and ready
starting projection
parsing type:  8  for length:  4 <Buffer aa 55 aa 55 04 00 00 00 08 00 00 00 f7 ff ff ff>
parsing 8 <Buffer e8 03 00 00>
Carplay message:  Support Wifi
unkown type:  13  with data::  <Buffer aa 55 aa 55 0d 00 00 00 0d 00 00 00 f2 ff ff ff>
unkown type:  14  with data::  <Buffer aa 55 aa 55 0d 00 00 00 0e 00 00 00 f1 ff ff ff>
unkown type:  18  with data::  <Buffer aa 55 aa 55 26 00 00 00 12 00 00 00 ed ff ff ff>
parsing type:  8  for length:  4 <Buffer aa 55 aa 55 04 00 00 00 08 00 00 00 f7 ff ff ff>
parsing 8 <Buffer e9 03 00 00>
Carplay message:  undefined
test message i
parsing type:  8  for length:  4 <Buffer aa 55 aa 55 04 00 00 00 08 00 00 00 f7 ff ff ff>
parsing 8 <Buffer 0f 00 00 00>
Carplay message:  undefined
test message
parsing type:  204  for length:  32 <Buffer aa 55 aa 55 20 00 00 00 cc 00 00 00 33 ff ff ff>
parsing 204 <Buffer 32 30 32 30 2e 31 30 2e 32 37 2e 31 32 33 39 43 41 59 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
version number:  2020.10.27.1239CAY
unkown type:  1  with data::  <Buffer aa 55 aa 55 1c 00 00 00 01 00 00 00 fe ff ff ff>
-----

but

web page doesn't open at browser...

**Comment by rubyon** [comment]
please write... this guide...

[](https://github.com/)............. DNS ............. DHCP ............. Network (iptables) ............. NGINX ............. Node ............. Tesla Carplay (with pm2)

**Comment by marcdubois71450** [comment]
Currently I have some problem with the bluetooth is the basic debian system. I have to try with rasberryOS. So before completing the doc I prefer to finish the project correctly, so that it is 100% functional.

And it is normal that the web page does not open, it will be hosted by nginx later in the documentation.
You can already find the nginx doc here: `https://github.com/marcdubois71450/tesla-carplay/blob/master/conf/carplay.conf`

**Comment by rubyon** [comment]
I see. thanks!

**Comment by rubyon** [comment]
<img width="1075" alt="스크린샷 2022-02-04 오전 2 05 54" src="https://user-images.githubusercontent.com/1408770/152392558-a50dd191-1bb6-427c-9637-aeae229c1365.png">

Thanks It Work!!!

**Comment by marcdubois71450** [comment]
I updated the doc, the sound in bluetooth finally works! I close
