### ISSUE TITLE
Not available for Model Y

### ISSUE THREAD

**Issue by BleuRain** [marcdubois71450/tesla-carplay#16]
Car:
Model Y

System Software Version:
v11.0 (2022.12.3.16 Odeb51535534)

Discribe:
When switching to D gear, R gear, the screen will freeze.

Is there any way to solve it？

**Comment by ikonopistsev** [comment]
I have the same problem in model 3, tesla blocked video playback in drive mode.

**Comment by marcdubois71450** [comment]
Fix on v0.4
