### ISSUE TITLE
Which hardware?

### ISSUE THREAD

**Issue by dmurray14** [marcdubois71450/tesla-carplay#17]
Which hardware works with this library? I see mention of the Carlinkit hardware, and I purchased this one:

https://www.amazon.com/Carlinkit-4-0-Adapter-Wireless-CarPlay/dp/B0B1Q819KM

But it doesn't seem to work. Looks like the USB identifiers are different. I changed them in the node-carplay library and got it to detect the hardware and looked like it would start projecting, but it doesn't seem to work.

Is the 3.0 version better? Would prefer to buy the right one rather than trial and error.

**Comment by marcdubois71450** [comment]
I am using version 2.0 for this test. For more information look at [node-CarPlay](https://github.com/rhysmorgan134/node-CarPlay) to see which carlinkit adapter to choose. (I see that the last commit adds the compatibility of an additional adapter.)
