### ISSUE TITLE
Tesla-doc.md error

### ISSUE THREAD

**Issue by psmith3** [marcdubois71450/tesla-carplay#2]
In following your documentation, I downloaded the operating system as instructed and configured SSH, pi password, hostname, and Wi-Fi settings in the installer and then wrote to the SD card. Once the pi is on the network, I was able to SSH into the hostname I added. However, the apt install update and upgrade commands do not work. The correct commands are:
```
sudo apt-get update 
sudo apt-get upgrade
sudo reboot
```

**Comment by marcdubois71450** [comment]
Thank you I corrected that for `apt`, on the other hand the `reboot` does not need `sudo` because it is carried out in `root`.

[https://github.com/marcdubois71450/tesla-carplay/commit/176cd8aa0c00fab5b5984903c71b8d100f07a918](commit)

**Comment by psmith3** [comment]
FYI, sudo reboot is required when connecting through SSH with the pi username. Same applies to the commands above. I enabled SSH and Wi-Fi from the Imager first.

**Comment by marcdubois71450** [comment]
In the documentation I make you log in to the root account before rebooting

**Comment by psmith3** [comment]
> 

Correct. However, I was logging in via SSH from the very beginning because I enabled it from the imager. Probably if I was connected directly with a keyboard, your instructions are right. Since I did not have a keyboard, mouse, and monitor handy, here is what I set in the imager and it allowed me to connect over Wi-Fi and/or ethernet using the pi login. I had to enable logging in via SSH with root like your instructions pointed out and that is where I picked your instructions back up.

![image](https://user-images.githubusercontent.com/14373163/155435552-0bfebc8d-623c-478e-b434-fed1de59dada.png)

![image](https://user-images.githubusercontent.com/14373163/155435629-67143f73-cc00-4cd6-8555-29267451bad0.png)

![image](https://user-images.githubusercontent.com/14373163/155435672-477a0fee-41ad-48be-be1c-710e266b166b.png)

One more item I found that needs to be installed is git. 
```
root@carplay:~# cd && git clone https://github.com/Arkq/bluez-alsa.git
-bash: git: command not found
```

```
apt install git
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  git-man liberror-perl
Suggested packages:
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-cvs git-mediawiki git-svn
The following NEW packages will be installed:
  git git-man liberror-perl
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 7,287 kB of archives.
After this operation, 37.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://deb.debian.org/debian bullseye/main arm64 liberror-perl all 0.17029-1 [31.0 kB]
Get:2 http://deb.debian.org/debian bullseye/main arm64 git-man all 1:2.30.2-1 [1,827 kB]
Get:3 http://deb.debian.org/debian bullseye/main arm64 git arm64 1:2.30.2-1 [5,428 kB]
Fetched 7,287 kB in 0s (14.9 MB/s)
Selecting previously unselected package liberror-perl.
(Reading database ... 39755 files and directories currently installed.)
Preparing to unpack .../liberror-perl_0.17029-1_all.deb ...
Unpacking liberror-perl (0.17029-1) ...
Selecting previously unselected package git-man.
Preparing to unpack .../git-man_1%3a2.30.2-1_all.deb ...
Unpacking git-man (1:2.30.2-1) ...
Selecting previously unselected package git.
Preparing to unpack .../git_1%3a2.30.2-1_arm64.deb ...
Unpacking git (1:2.30.2-1) ...
Setting up liberror-perl (0.17029-1) ...
Setting up git-man (1:2.30.2-1) ...
Setting up git (1:2.30.2-1) ...
Processing triggers for man-db (2.9.4-2) ...
root@carplay:~# 
```

Hope this all helps you out.

**Comment by marcdubois71450** [comment]
Ok I understand better for the sudo reboot then!
Yes, it's good to correct the details, it makes life easier for the installation! Thank you !
