### ISSUE TITLE
codec-msbc.h:25:10: fatal error: spandsp.h: No such file or directory

### ISSUE THREAD

**Issue by psmith3** [marcdubois71450/tesla-carplay#3]
Running into a snag when getting to `root@carplay:/bluez-alsa/build# make && sudo make install` and get the following error and cannot find a way around it. Have you seen this?

`gcc -DHAVE_CONFIG_H -I. -I../../src -I..    -pthread -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include  -g -O0 -MT sco.o -MD -MP -MF $depbase.Tpo -c -o sco.o ../../src/sco.c &&\
mv -f $depbase.Tpo $depbase.Po
In file included from ../../src/sco.c:29:
../../src/codec-msbc.h:25:10: fatal error: spandsp.h: No such file or directory
   25 | #include <spandsp.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:717: sco.o] Error 1
make[3]: Leaving directory '/bluez-alsa/build/src'
make[2]: *** [Makefile:774: all-recursive] Error 1
make[2]: Leaving directory '/bluez-alsa/build/src'
make[1]: *** [Makefile:457: all-recursive] Error 1
make[1]: Leaving directory '/bluez-alsa/build'
make: *** [Makefile:389: all] Error 2
`

**Comment by marcdubois71450** [comment]
Try : 
`apt install libspandsp-dev`
And retest `make && sudo make install`
tell me if it works

**Comment by psmith3** [comment]
> Try :
> `apt install libspandsp-dev -y`
> And retest `make && sudo make install`
> tell me if it works

Simple as that and that worked. Looks like `libspandsp-dev` needs to be added. Thanks!

**Comment by marcdubois71450** [comment]
Thanks for your feedback!
I add it to the documentation!

[commit](https://github.com/marcdubois71450/tesla-carplay/commit/3f3a2d69df2dedd2d83fa311c67fd958708605bd)
