### ISSUE TITLE
ExecStart=/usr/lib/bluetooth/bluetoothd --noplugin=sap --plugin=a2dp Step

### ISSUE THREAD

**Issue by psmith3** [marcdubois71450/tesla-carplay#6]
This step is wrong

In nano /etc/systemd/system/bluetooth.target.wants/bluetooth.service, 

`ExecStart=/usr/lib/bluetooth/bluetoothd --noplugin=sap --plugin=a2dp `

Should be 

`ExecStart=/usr/libexec/bluetooth/bluetoothd --noplugin=sap --plugin=a2dp `

**Comment by ElijahLynn** [comment]
Thanks for this, you unintentionally helped me with an issue I was having with enabling an experimental feature to get the battery level from my headphones with Pipewire, bluetoothd and Linux! On Arch Linux my path is the former and the advice was to use the later, which wasn't working.

https://www.redpill-linpro.com/techblog/2021/05/31/better-bluetooth-headset-audio-with-msbc.html

**Comment by marcdubois71450** [comment]
> Thanks for this, you unintentionally helped me with an issue I was having with enabling an experimental feature to get the battery level from my headphones with Pipewire, bluetoothd and Linux! On Arch Linux my path is the former and the advice was to use the later, which wasn't working.
> 
> https://www.redpill-linpro.com/techblog/2021/05/31/better-bluetooth-headset-audio-with-msbc.html

Your article made me discover a lot of things about bluetooth and linux, especially since I'm trying to integrate the steering wheel controls and the microphone theoretically available in bluetooth.

Thank you

**Comment by marcdubois71450** [comment]
> ExecStart=/usr/libexec/bluetooth/bluetoothd --noplugin=sap --plugin=a2dp

I just checked it's correct thank you it must have blocked all those who tested it, I corrected the documentation.
