### ISSUE TITLE
Stolen License / Stolen credits

### ISSUE THREAD

**Issue by darreal44** [marcdubois71450/tesla-carplay#8]
This guy is stealing credits from the original owner: https://github.com/electric-monk/pycarplay
He even changed license name to his in order to seem more legit.

**Comment by darreal44** [comment]
Pardon il s'agit d'une erreur

**Comment by marcdubois71450** [comment]
Hi darreal44, 

Actually my code is based on this [library](https://github.com/rhysmorgan134/node-CarPlay
)
(Which by the way it's inspired by pycarplay)

I just [modified](https://github.com/marcdubois71450/tesla-carplay/commit/7261bf0a160c12342cbd46bd1654e6a2e1e27edd
) the Readme to explain it.

It's enough ? Or should I change or remove the [LICENSE?](https://github.com/marcdubois71450/tesla-carplay/blob/master/LICENSE)

Thanks
